# Copyright 2021 Google LLC. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
info:
  title: Monitoring/Service
  description: DCL Specification for the Monitoring Service resource
  x-dcl-has-iam: false
paths:
  get:
    description: The function used to get information about a Service
    parameters:
    - name: Service
      required: true
      description: A full instance of a Service
  apply:
    description: The function used to apply information about a Service
    parameters:
    - name: Service
      required: true
      description: A full instance of a Service
  delete:
    description: The function used to delete a Service
    parameters:
    - name: Service
      required: true
      description: A full instance of a Service
  deleteAll:
    description: The function used to delete all Service
    parameters:
    - name: project
      required: true
      schema:
        type: string
  list:
    description: The function used to list information about many Service
    parameters:
    - name: project
      required: true
      schema:
        type: string
components:
  schemas:
    Service:
      title: Service
      x-dcl-id: projects/{{project}}/services/{{name}}
      x-dcl-parent-container: project
      type: object
      required:
      - name
      - project
      properties:
        appEngine:
          type: object
          x-dcl-go-name: AppEngine
          x-dcl-go-type: ServiceAppEngine
          description: Type used for App Engine services.
          x-dcl-conflicts:
          - custom
          - cloudEndpoints
          - clusterIstio
          - meshIstio
          - istioCanonicalService
          - cloudRun
          - gkeNamespace
          - gkeWorkload
          - gkeService
          properties:
            moduleId:
              type: string
              x-dcl-go-name: ModuleId
              description: 'The ID of the App Engine module underlying this service.
                Corresponds to the `module_id` resource label in the `gae_app` monitored
                resource: https://cloud.google.com/monitoring/api/resources#tag_gae_app'
        cloudEndpoints:
          type: object
          x-dcl-go-name: CloudEndpoints
          x-dcl-go-type: ServiceCloudEndpoints
          description: Type used for Cloud Endpoints services.
          x-dcl-conflicts:
          - custom
          - appEngine
          - clusterIstio
          - meshIstio
          - istioCanonicalService
          - cloudRun
          - gkeNamespace
          - gkeWorkload
          - gkeService
          properties:
            service:
              type: string
              x-dcl-go-name: Service
              description: 'The name of the Cloud Endpoints service underlying this
                service. Corresponds to the `service` resource label in the `api`
                monitored resource: https://cloud.google.com/monitoring/api/resources#tag_api'
        cloudRun:
          type: object
          x-dcl-go-name: CloudRun
          x-dcl-go-type: ServiceCloudRun
          description: Type used for Cloud Run services.
          x-dcl-conflicts:
          - custom
          - appEngine
          - cloudEndpoints
          - clusterIstio
          - meshIstio
          - istioCanonicalService
          - gkeNamespace
          - gkeWorkload
          - gkeService
          properties:
            location:
              type: string
              x-dcl-go-name: Location
              description: 'The location the service is run. Corresponds to the `location`
                resource label in the `cloud_run_revision` monitored resource: https://cloud.google.com/monitoring/api/resources#tag_cloud_run_revision'
            serviceName:
              type: string
              x-dcl-go-name: ServiceName
              description: 'The name of the Cloud Run service. Corresponds to the
                `service_name` resource label in the `cloud_run_revision` monitored
                resource: https://cloud.google.com/monitoring/api/resources#tag_cloud_run_revision'
        clusterIstio:
          type: object
          x-dcl-go-name: ClusterIstio
          x-dcl-go-type: ServiceClusterIstio
          description: Type used for Istio services that live in a Kubernetes cluster.
          x-dcl-conflicts:
          - custom
          - appEngine
          - cloudEndpoints
          - meshIstio
          - istioCanonicalService
          - cloudRun
          - gkeNamespace
          - gkeWorkload
          - gkeService
          properties:
            clusterName:
              type: string
              x-dcl-go-name: ClusterName
              description: The name of the Kubernetes cluster in which this Istio
                service is defined. Corresponds to the `cluster_name` resource label
                in `k8s_cluster` resources.
            location:
              type: string
              x-dcl-go-name: Location
              description: The location of the Kubernetes cluster in which this Istio
                service is defined. Corresponds to the `location` resource label in
                `k8s_cluster` resources.
            serviceName:
              type: string
              x-dcl-go-name: ServiceName
              description: The name of the Istio service underlying this service.
                Corresponds to the `destination_service_name` metric label in Istio
                metrics.
            serviceNamespace:
              type: string
              x-dcl-go-name: ServiceNamespace
              description: The namespace of the Istio service underlying this service.
                Corresponds to the `destination_service_namespace` metric label in
                Istio metrics.
        custom:
          type: object
          x-dcl-go-name: Custom
          x-dcl-go-type: ServiceCustom
          description: Custom service type.
          x-dcl-conflicts:
          - appEngine
          - cloudEndpoints
          - clusterIstio
          - meshIstio
          - istioCanonicalService
          - cloudRun
          - gkeNamespace
          - gkeWorkload
          - gkeService
          x-dcl-send-empty: true
        deleted:
          type: boolean
          x-dcl-go-name: Deleted
          description: Indicated whether the resource has been deleted. If this is
            true, the Service will only appear in calls to ListServices that specify
            show_deleted
        displayName:
          type: string
          x-dcl-go-name: DisplayName
          description: Name used for UI elements listing this Service.
        gkeNamespace:
          type: object
          x-dcl-go-name: GkeNamespace
          x-dcl-go-type: ServiceGkeNamespace
          description: Type used for GKE Namespaces.
          x-dcl-conflicts:
          - custom
          - appEngine
          - cloudEndpoints
          - clusterIstio
          - meshIstio
          - istioCanonicalService
          - cloudRun
          - gkeWorkload
          - gkeService
          properties:
            clusterName:
              type: string
              x-dcl-go-name: ClusterName
              description: The name of the parent cluster.
            location:
              type: string
              x-dcl-go-name: Location
              description: The location of the parent cluster. This may be a zone
                or region.
            namespaceName:
              type: string
              x-dcl-go-name: NamespaceName
              description: The name of this namespace.
            projectId:
              type: string
              x-dcl-go-name: ProjectId
              readOnly: true
              description: Output only. The project this resource lives in. For legacy
                services migrated from the `Custom` type, this may be a distinct project
                from the one parenting the service itself.
        gkeService:
          type: object
          x-dcl-go-name: GkeService
          x-dcl-go-type: ServiceGkeService
          description: Type used for GKE Services (the Kubernetes concept of a service).
          x-dcl-conflicts:
          - custom
          - appEngine
          - cloudEndpoints
          - clusterIstio
          - meshIstio
          - istioCanonicalService
          - cloudRun
          - gkeNamespace
          - gkeWorkload
          properties:
            clusterName:
              type: string
              x-dcl-go-name: ClusterName
              description: The name of the parent cluster.
            location:
              type: string
              x-dcl-go-name: Location
              description: The location of the parent cluster. This may be a zone
                or region.
            namespaceName:
              type: string
              x-dcl-go-name: NamespaceName
              description: The name of the parent namespace.
            projectId:
              type: string
              x-dcl-go-name: ProjectId
              readOnly: true
              description: Output only. The project this resource lives in. For legacy
                services migrated from the `Custom` type, this may be a distinct project
                from the one parenting the service itself.
            serviceName:
              type: string
              x-dcl-go-name: ServiceName
              description: The name of this service.
        gkeWorkload:
          type: object
          x-dcl-go-name: GkeWorkload
          x-dcl-go-type: ServiceGkeWorkload
          description: Type used for GKE Workloads.
          x-dcl-conflicts:
          - custom
          - appEngine
          - cloudEndpoints
          - clusterIstio
          - meshIstio
          - istioCanonicalService
          - cloudRun
          - gkeNamespace
          - gkeService
          properties:
            clusterName:
              type: string
              x-dcl-go-name: ClusterName
              description: The name of the parent cluster.
            location:
              type: string
              x-dcl-go-name: Location
              description: The location of the parent cluster. This may be a zone
                or region.
            namespaceName:
              type: string
              x-dcl-go-name: NamespaceName
              description: The name of the parent namespace.
            projectId:
              type: string
              x-dcl-go-name: ProjectId
              readOnly: true
              description: Output only. The project this resource lives in. For legacy
                services migrated from the `Custom` type, this may be a distinct project
                from the one parenting the service itself.
            topLevelControllerName:
              type: string
              x-dcl-go-name: TopLevelControllerName
              description: The name of this workload.
            topLevelControllerType:
              type: string
              x-dcl-go-name: TopLevelControllerType
              description: The type of this workload (e.g. "Deployment" or "DaemonSet")
        istioCanonicalService:
          type: object
          x-dcl-go-name: IstioCanonicalService
          x-dcl-go-type: ServiceIstioCanonicalService
          description: Type used for canonical services scoped to an Istio mesh. Metrics
            for Istio are [documented here](https://istio.io/latest/docs/reference/config/metrics/)
          x-dcl-conflicts:
          - custom
          - appEngine
          - cloudEndpoints
          - clusterIstio
          - meshIstio
          - cloudRun
          - gkeNamespace
          - gkeWorkload
          - gkeService
          properties:
            canonicalService:
              type: string
              x-dcl-go-name: CanonicalService
              description: The name of the canonical service underlying this service.
                Corresponds to the `destination_canonical_service_name` metric label
                in label in [Istio metrics](https://cloud.google.com/monitoring/api/metrics_istio).
            canonicalServiceNamespace:
              type: string
              x-dcl-go-name: CanonicalServiceNamespace
              description: The namespace of the canonical service underlying this
                service. Corresponds to the `destination_canonical_service_namespace`
                metric label in [Istio metrics](https://cloud.google.com/monitoring/api/metrics_istio).
            meshUid:
              type: string
              x-dcl-go-name: MeshUid
              description: Identifier for the Istio mesh in which this canonical service
                is defined. Corresponds to the `mesh_uid` metric label in [Istio metrics](https://cloud.google.com/monitoring/api/metrics_istio).
        meshIstio:
          type: object
          x-dcl-go-name: MeshIstio
          x-dcl-go-type: ServiceMeshIstio
          description: Type used for Istio services scoped to an Istio mesh.
          x-dcl-conflicts:
          - custom
          - appEngine
          - cloudEndpoints
          - clusterIstio
          - istioCanonicalService
          - cloudRun
          - gkeNamespace
          - gkeWorkload
          - gkeService
          properties:
            meshUid:
              type: string
              x-dcl-go-name: MeshUid
              description: Identifier for the mesh in which this Istio service is
                defined. Corresponds to the `mesh_uid` metric label in Istio metrics.
            serviceName:
              type: string
              x-dcl-go-name: ServiceName
              description: The name of the Istio service underlying this service.
                Corresponds to the `destination_service_name` metric label in Istio
                metrics.
            serviceNamespace:
              type: string
              x-dcl-go-name: ServiceNamespace
              description: The namespace of the Istio service underlying this service.
                Corresponds to the `destination_service_namespace` metric label in
                Istio metrics.
        name:
          type: string
          x-dcl-go-name: Name
          description: 'Resource name for this Service. The format is: projects/[PROJECT_ID_OR_NUMBER]/services/[SERVICE_ID]'
        project:
          type: string
          x-dcl-go-name: Project
          description: The project for the resource
          x-kubernetes-immutable: true
          x-dcl-references:
          - resource: Cloudresourcemanager/Project
            field: name
            parent: true
        telemetry:
          type: object
          x-dcl-go-name: Telemetry
          x-dcl-go-type: ServiceTelemetry
          description: Configuration for how to query telemetry on a Service.
          properties:
            resourceName:
              type: string
              x-dcl-go-name: ResourceName
              description: The full name of the resource that defines this service.
                Formatted as described in https://cloud.google.com/apis/design/resource_names.
        userLabels:
          type: object
          additionalProperties:
            type: string
          x-dcl-go-name: UserLabels
          description: Labels which have been used to annotate the service. Label
            keys must start with a letter. Label keys and values may contain lowercase
            letters, numbers, underscores, and dashes. Label keys and values have
            a maximum length of 63 characters, and must be less than 128 bytes in
            size. Up to 64 label entries may be stored. For labels which do not have
            a semantic value, the empty string may be supplied for the label value.
