# Copyright 2021 Google LLC. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("//:connector_rules.bzl", "connector")
connector(name="compute/beta", resources=["address","autoscaler","backend_bucket","disk","firewall","firewall_policy","firewall_policy_association","firewall_policy_rule","forwarding_rule","health_check","http_health_check","https_health_check","image","instance","instance_group_manager","instance_template","managed_ssl_certificate","network","network_endpoint","network_endpoint_group","reservation","route","router","router_peer","snapshot","ssl_certificate","ssl_policy","subnetwork","target_http_proxy","target_pool","target_ssl_proxy","target_vpn_gateway","url_map","vpn_gateway","vpn_tunnel"])
