# Copyright 2021 Google LLC. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
components:
  schemas:
    Database:
      properties:
        ddl:
          description: 'An optional list of DDL statements to run inside the newly
            created database. Statements can create tables, indexes, etc. These statements
            execute atomically with the creation of the database: if there is an error
            in any statement, the database is not created.'
          items:
            type: string
            x-dcl-go-type: string
          type: array
          x-dcl-go-name: Ddl
          x-dcl-list-type: list
          x-kubernetes-immutable: true
        instance:
          description: The instance to create the database on.
          type: string
          x-dcl-go-name: Instance
          x-dcl-references:
          - field: name
            parent: true
            resource: Spanner/Instance
          x-kubernetes-immutable: true
        name:
          description: A unique identifier for the database, which cannot be changed
            after the instance is created. Values are of the form \[a-z\]\[-a-z0-9\]\*\[a-z0-9\].
          type: string
          x-dcl-go-name: Name
          x-kubernetes-immutable: true
        project:
          description: The ID of the project in which the resource belongs.
          type: string
          x-dcl-go-name: Project
          x-kubernetes-immutable: true
        state:
          description: The current database state.
          enum:
          - CREATING
          - READY
          readOnly: true
          type: string
          x-dcl-go-name: State
          x-dcl-go-type: DatabaseStateEnum
          x-kubernetes-immutable: true
      required:
      - name
      - instance
      - project
      title: Database
      type: object
      x-dcl-id: projects/{{project}}/instances/{{instance}}/databases/{{name}}
      x-dcl-locations: []
      x-dcl-parent-container: project
      x-dcl-uses-state-hint: false
info:
  description: DCL Specification for the Spanner Database resource
  title: Spanner/Database
  x-dcl-has-iam: false
paths:
  list:
    description: The function called used to list information about many Database
    parameters:
    - name: project
      required: true
    - name: name
      required: true
