# Copyright 2021 Google LLC. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
components:
  schemas:
    Config:
      properties:
        description:
          description: An optional description of the runtime config.
          type: string
          x-dcl-go-name: Description
        name:
          description: The name of the runtime config.
          type: string
          x-dcl-go-name: Name
          x-kubernetes-immutable: true
        project:
          description: The ID of the project in which the resource belongs.
          type: string
          x-dcl-go-name: Project
          x-dcl-references:
          - field: name
            parent: true
            resource: Cloudresourcemanager/Project
          x-kubernetes-immutable: true
      required:
      - name
      - project
      title: Config
      type: object
      x-dcl-id: projects/{{project}}/configs/{{name}}
      x-dcl-locations: []
      x-dcl-parent-container: project
      x-dcl-uses-state-hint: false
info:
  description: DCL Specification for the RuntimeConfig Config resource
  title: RuntimeConfig/Config
  x-dcl-has-iam: false
paths:
  apply:
    description: The function used to apply information about a Config
    parameters:
    - description: A full instance of a Config
      name: Config
      required: true
  delete:
    description: The function used to delete a Config
    parameters:
    - description: A full instance of a Config
      name: Config
      required: true
  deleteAll:
    description: The function used to delete all Config
    parameters:
    - name: project
      required: true
      schema:
        type: string
    - name: name
      required: true
      schema:
        type: string
  get:
    description: The function used to get information about a Config
    parameters:
    - description: A full instance of a Config
      name: Config
      required: true
  list:
    description: The function used to list information about many Config
    parameters:
    - name: project
      required: true
      schema:
        type: string
    - name: name
      required: true
      schema:
        type: string
