# Copyright 2021 Google LLC. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
components:
  schemas:
    Database:
      properties:
        charset:
          description: The Cloud SQL charset value.
          type: string
          x-dcl-go-name: Charset
          x-dcl-server-default: true
        collation:
          description: The Cloud SQL collation value.
          type: string
          x-dcl-go-name: Collation
          x-dcl-server-default: true
        instance:
          description: The name of the Cloud SQL instance. This does not include the
            project ID.
          type: string
          x-dcl-go-name: Instance
          x-kubernetes-immutable: true
        name:
          description: The name of the database in the Cloud SQL instance. This does
            not include the project ID or instance name.
          type: string
          x-dcl-go-name: Name
          x-kubernetes-immutable: true
        project:
          description: The project ID of the project containing the Cloud SQL database.
            The Google apps domain is prefixed if applicable.
          type: string
          x-dcl-go-name: Project
          x-kubernetes-immutable: true
        selfLink:
          description: The URI of this resource.
          readOnly: true
          type: string
          x-dcl-go-name: SelfLink
          x-kubernetes-immutable: true
      required:
      - instance
      - name
      title: Database
      type: object
      x-dcl-id: projects/{{project}}/instances/{{instance}}/databases/{{name}}
      x-dcl-locations: []
      x-dcl-parent-container: project
      x-dcl-uses-state-hint: false
info:
  description: DCL Specification for the Sql Database resource
  title: Sql/Database
  x-dcl-has-iam: false
paths:
  list:
    description: The function called used to list information about many Database
    parameters:
    - name: project
      required: true
    - name: instance
      required: true
