# Copyright 2021 Google LLC. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
info:
  title: Sql/Database
  description: DCL Specification for the Sql Database resource
  x-dcl-has-iam: false
paths:
  get:
    description: The function used to get information about a Database
    parameters:
    - name: Database
      required: true
      description: A full instance of a Database
  apply:
    description: The function used to apply information about a Database
    parameters:
    - name: Database
      required: true
      description: A full instance of a Database
  delete:
    description: The function used to delete a Database
    parameters:
    - name: Database
      required: true
      description: A full instance of a Database
  deleteAll:
    description: The function used to delete all Database
    parameters:
    - name: project
      required: true
      schema:
        type: string
    - name: instance
      required: true
      schema:
        type: string
  list:
    description: The function used to list information about many Database
    parameters:
    - name: project
      required: true
      schema:
        type: string
    - name: instance
      required: true
      schema:
        type: string
components:
  schemas:
    Database:
      title: Database
      x-dcl-id: projects/{{project}}/instances/{{instance}}/databases/{{name}}
      x-dcl-parent-container: project
      type: object
      required:
      - instance
      - name
      properties:
        charset:
          type: string
          x-dcl-go-name: Charset
          description: The Cloud SQL charset value.
          x-dcl-server-default: true
        collation:
          type: string
          x-dcl-go-name: Collation
          description: The Cloud SQL collation value.
          x-dcl-server-default: true
        instance:
          type: string
          x-dcl-go-name: Instance
          description: The name of the Cloud SQL instance. This does not include the
            project ID.
          x-kubernetes-immutable: true
        name:
          type: string
          x-dcl-go-name: Name
          description: The name of the database in the Cloud SQL instance. This does
            not include the project ID or instance name.
          x-kubernetes-immutable: true
        project:
          type: string
          x-dcl-go-name: Project
          description: The project ID of the project containing the Cloud SQL database.
            The Google apps domain is prefixed if applicable.
          x-kubernetes-immutable: true
          x-dcl-references:
          - resource: Cloudresourcemanager/Project
            field: name
            parent: true
        selfLink:
          type: string
          x-dcl-go-name: SelfLink
          readOnly: true
          description: The URI of this resource.
          x-kubernetes-immutable: true
