# Copyright 2021 Google LLC. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
info:
  title: AppEngine/Application
  description: DCL Specification for the AppEngine Application resource
  x-dcl-has-iam: false
paths:
  get:
    description: The function used to get information about a Application
    parameters:
    - name: Application
      required: true
      description: A full instance of a Application
  apply:
    description: The function used to apply information about a Application
    parameters:
    - name: Application
      required: true
      description: A full instance of a Application
components:
  schemas:
    Application:
      title: Application
      x-dcl-id: apps/{{name}}
      x-dcl-uses-state-hint: true
      type: object
      properties:
        authDomain:
          type: string
          x-dcl-go-name: AuthDomain
          description: Google Apps authentication domain that controls which users
            can access this application. Defaults to open access for any Google Account.
        codeBucket:
          type: string
          x-dcl-go-name: CodeBucket
          readOnly: true
          description: Google Cloud Storage bucket that can be used for storing files
            associated with this application. This bucket is associated with the application
            and can be used by the gcloud deployment commands. @OutputOnly
          x-kubernetes-immutable: true
        databaseType:
          type: string
          x-dcl-go-name: DatabaseType
          x-dcl-go-type: ApplicationDatabaseTypeEnum
          description: 'The type of the Cloud Firestore or Cloud Datastore database
            associated with this application. Possible values: DATABASE_TYPE_UNSPECIFIED,
            CLOUD_DATASTORE, CLOUD_FIRESTORE, CLOUD_DATASTORE_COMPATIBILITY'
          enum:
          - DATABASE_TYPE_UNSPECIFIED
          - CLOUD_DATASTORE
          - CLOUD_FIRESTORE
          - CLOUD_DATASTORE_COMPATIBILITY
        defaultBucket:
          type: string
          x-dcl-go-name: DefaultBucket
          readOnly: true
          description: Google Cloud Storage bucket that can be used by this application
            to store content. @OutputOnly
          x-kubernetes-immutable: true
        defaultCookieExpiration:
          type: string
          x-dcl-go-name: DefaultCookieExpiration
          description: 'Cookie expiration policy for this application. A duration
            in seconds with up to nine fractional digits, terminated by ''s''. Example:
            "3.5s".'
        defaultHostname:
          type: string
          x-dcl-go-name: DefaultHostname
          readOnly: true
          description: Hostname used to reach this application, as resolved by App
            Engine. @OutputOnly
          x-kubernetes-immutable: true
        dispatchRules:
          type: array
          x-dcl-go-name: DispatchRules
          description: HTTP path dispatch rules for requests to the application that
            do not explicitly target a service or version. Rules are order-dependent.
            Up to 20 dispatch rules can be supported.
          x-dcl-list-type: list
          items:
            type: object
            x-dcl-go-type: ApplicationDispatchRules
            properties:
              domain:
                type: string
                x-dcl-go-name: Domain
                description: 'Domain name to match against. The wildcard "`*`" is
                  supported if specified before a period: "`*.`". Defaults to matching
                  all domains: "`*`".'
              path:
                type: string
                x-dcl-go-name: Path
                description: Pathname within the host. Must start with a "`/`". A
                  single "`*`" can be included at the end of the path. The sum of
                  the lengths of the domain and path may not exceed 100 characters.
              service:
                type: string
                x-dcl-go-name: Service
                description: 'Resource ID of a service in this application that should
                  serve the matched request. The service must already exist. Example:
                  `default`.'
        featureSettings:
          type: object
          x-dcl-go-name: FeatureSettings
          x-dcl-go-type: ApplicationFeatureSettings
          description: The feature specific settings to be used in the application.
          properties:
            splitHealthChecks:
              type: boolean
              x-dcl-go-name: SplitHealthChecks
              description: Boolean value indicating if split health checks should
                be used instead of the legacy health checks. At an app.yaml level,
                this means defaulting to 'readiness_check' and 'liveness_check' values
                instead of 'health_check' ones. Once the legacy 'health_check' behavior
                is deprecated, and this value is always true, this setting can be
                removed.
            useContainerOptimizedOS:
              type: boolean
              x-dcl-go-name: UseContainerOptimizedOS
              description: If true, use [Container-Optimized OS](https://cloud.google.com/container-optimized-os/)
                base image for VMs, rather than a base Debian image.
        gcrDomain:
          type: string
          x-dcl-go-name: GcrDomain
          description: The Google Container Registry domain used for storing managed
            build docker images for this application.
        iap:
          type: object
          x-dcl-go-name: Iap
          x-dcl-go-type: ApplicationIap
          description: Identity Aware Proxy.
          x-kubernetes-immutable: true
          properties:
            enabled:
              type: boolean
              x-dcl-go-name: Enabled
              description: Whether the serving infrastructure will authenticate and
                authorize all incoming requests. If true, the `oauth2_client_id` and
                `oauth2_client_secret` fields must be non-empty.
              x-kubernetes-immutable: true
            oauth2ClientId:
              type: string
              x-dcl-go-name: OAuth2ClientId
              description: OAuth2 client ID to use for the authentication flow.
              x-kubernetes-immutable: true
            oauth2ClientSecret:
              type: string
              x-dcl-go-name: OAuth2ClientSecret
              description: OAuth2 client secret to use for the authentication flow.
                For security reasons, this value cannot be retrieved via the API.
                Instead, the SHA-256 hash of the value is returned in the `oauth2_client_secret_sha256`
                field. @InputOnly
              x-kubernetes-immutable: true
              x-dcl-sensitive: true
              x-dcl-mutable-unreadable: true
            oauth2ClientSecretSha256:
              type: string
              x-dcl-go-name: OAuth2ClientSecretSha256
              readOnly: true
              description: Hex-encoded SHA-256 hash of the client secret. @OutputOnly
              x-kubernetes-immutable: true
        location:
          type: string
          x-dcl-go-name: Location
          description: Location from which this application runs. Application instances
            run out of the data centers in the specified location, which is also where
            all of the application's end user content is stored. Defaults to `us-central`.
            View the list of [supported locations](https://cloud.google.com/appengine/docs/locations).
          x-kubernetes-immutable: true
        name:
          type: string
          x-dcl-go-name: Name
          description: The name of the application
          x-kubernetes-immutable: true
        servingStatus:
          type: string
          x-dcl-go-name: ServingStatus
          x-dcl-go-type: ApplicationServingStatusEnum
          description: 'Serving status of this application. Possible values: UNSPECIFIED,
            SERVING, USER_DISABLED, SYSTEM_DISABLED'
          enum:
          - UNSPECIFIED
          - SERVING
          - USER_DISABLED
          - SYSTEM_DISABLED
