// Copyright 2021 Google LLC. All Rights Reserved.
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// GENERATED BY gen_go_data.go
// gen_go_data -package cloudbilling -var YAML_project_billing_info blaze-out/k8-fastbuild/genfiles/cloud/graphite/mmv2/services/google/cloudbilling/project_billing_info.yaml

package cloudbilling

// blaze-out/k8-fastbuild/genfiles/cloud/graphite/mmv2/services/google/cloudbilling/project_billing_info.yaml
var YAML_project_billing_info = []byte("info:\n  title: CloudBilling/ProjectBillingInfo\n  description: DCL Specification for the CloudBilling ProjectBillingInfo resource\n  x-dcl-has-iam: false\npaths:\n  get:\n    description: The function used to get information about a ProjectBillingInfo\n    parameters:\n    - name: ProjectBillingInfo\n      required: true\n      description: A full instance of a ProjectBillingInfo\n  apply:\n    description: The function used to apply information about a ProjectBillingInfo\n    parameters:\n    - name: ProjectBillingInfo\n      required: true\n      description: A full instance of a ProjectBillingInfo\n  delete:\n    description: The function used to delete a ProjectBillingInfo\n    parameters:\n    - name: ProjectBillingInfo\n      required: true\n      description: A full instance of a ProjectBillingInfo\ncomponents:\n  schemas:\n    ProjectBillingInfo:\n      title: ProjectBillingInfo\n      x-dcl-id: projects/{{name}}/billingInfo\n      type: object\n      properties:\n        billingAccountName:\n          type: string\n          x-dcl-go-name: BillingAccountName\n          x-dcl-send-empty: true\n        billingEnabled:\n          type: string\n          x-dcl-go-name: BillingEnabled\n          readOnly: true\n          x-kubernetes-immutable: true\n        name:\n          type: string\n          x-dcl-go-name: Name\n          x-kubernetes-immutable: true\n")

// 1343 bytes
// MD5: 922f04bf8b75613db1c8ed45726e7dc5
