# Copyright 2021 Google LLC. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
info:
  title: Apigee/Environment
  description: DCL Specification for the Apigee Environment resource
  x-dcl-has-iam: true
paths:
  get:
    description: The function used to get information about a Environment
    parameters:
    - name: Environment
      required: true
      description: A full instance of a Environment
  apply:
    description: The function used to apply information about a Environment
    parameters:
    - name: Environment
      required: true
      description: A full instance of a Environment
  delete:
    description: The function used to delete a Environment
    parameters:
    - name: Environment
      required: true
      description: A full instance of a Environment
  deleteAll:
    description: The function used to delete all Environment
    parameters:
    - name: organization
      required: true
      schema:
        type: string
  list:
    description: The function used to list information about many Environment
    parameters:
    - name: organization
      required: true
      schema:
        type: string
components:
  schemas:
    Environment:
      title: Environment
      x-dcl-id: organizations/{{organization}}/environments/{{name}}
      x-dcl-parent-container: organization
      type: object
      required:
      - name
      - organization
      properties:
        createdAt:
          type: integer
          format: int64
          x-dcl-go-name: CreatedAt
          readOnly: true
          description: Output only. Creation time of this environment as milliseconds
            since epoch.
          x-kubernetes-immutable: true
        description:
          type: string
          x-dcl-go-name: Description
          description: Optional. Description of the environment.
          x-kubernetes-immutable: true
        displayName:
          type: string
          x-dcl-go-name: DisplayName
          description: Optional. Display name for this environment.
          x-kubernetes-immutable: true
        lastModifiedAt:
          type: integer
          format: int64
          x-dcl-go-name: LastModifiedAt
          readOnly: true
          description: Output only. Last modification time of this environment as
            milliseconds since epoch.
          x-kubernetes-immutable: true
        name:
          type: string
          x-dcl-go-name: Name
          description: Required. Name of the environment. Values must match the regular
            expression ^[.\p{Alnum}-_]{1,255}$
          x-kubernetes-immutable: true
        organization:
          type: string
          x-dcl-go-name: Organization
          description: The organization for the resource
          x-kubernetes-immutable: true
          x-dcl-references:
          - resource: Cloudresourcemanager/Organization
            field: name
            parent: true
        properties:
          type: object
          x-dcl-go-name: Properties
          x-dcl-go-type: EnvironmentProperties
          description: Optional. Key-value pairs that may be used for customizing
            the environment.
          x-kubernetes-immutable: true
          properties:
            property:
              type: array
              x-dcl-go-name: Property
              description: List of all properties in the object
              x-dcl-list-type: set
              items:
                type: object
                x-dcl-go-type: EnvironmentPropertiesProperty
                properties:
                  name:
                    type: string
                    x-dcl-go-name: Name
                    description: The property key
                    x-kubernetes-immutable: true
                  value:
                    type: string
                    x-dcl-go-name: Value
                    description: The property value
                    x-kubernetes-immutable: true
        state:
          type: string
          x-dcl-go-name: State
          x-dcl-go-type: EnvironmentStateEnum
          readOnly: true
          description: 'Output only. State of the environment. Values other than ACTIVE
            means the resource is not ready to use. Possible values: STATE_UNSPECIFIED,
            CREATING, ACTIVE, DELETING'
          x-kubernetes-immutable: true
          enum:
          - STATE_UNSPECIFIED
          - CREATING
          - ACTIVE
          - DELETING
